Numpy in Python

In [ ]:
import numpy as np

print(np.__version__)

1.22.4


In [ ]:
arr1=np.array([1,2,3,4,5,6,7,8,9])
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr2=np.array([1.5,2.5,3.5,4.5,5.0,6.0,7.0])
arr2

array([1.5, 2.5, 3.5, 4.5, 5. , 6. , 7. ])

In [ ]:
arr1.dtype

dtype('int64')

In [ ]:
arr1.astype('float')

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
arr3 = np.array([1,2,3,4,5],dtype='float32')
arr3

array([1., 2., 3., 4., 5.], dtype=float32)

In [ ]:
arr2.dtype

dtype('float64')

In [ ]:
# 1.An Array is create by list method:
Arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
Arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# 2.An array of length 10, filled with 0:
Arr2 = np.zeros(10)
Arr2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# 2.An array of length 5, filled with 1.0:
Arr2 = np.ones((5,2))
Arr2

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
# 3.Going up to 20
Arr3 = np.arange(0,20)
Arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# 4.An array of 5 numbers, linearly spaced between 10 and 20
Arr4 = np.linspace(10,20,5)
Arr4

array([10. , 12.5, 15. , 17.5, 20. ])

In [ ]:
# 5.An array of the given shape and populate it with random
# samples. You can also try using "randint" and "normal"
Arr5 = np.random.random((3, 3))
Arr5

array([[0.3998969 , 0.42519994, 0.30488944],
       [0.38314342, 0.53006944, 0.02102422],
       [0.71477081, 0.0522087 , 0.84672078]])

In [ ]:
# 6.using Identity funtion,
#daigonal are 1
Arr6 = np.identity(5)
Arr6

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# No. of dimensional array
print("Number of dimensions:-", Arr1.ndim)
print("Number of dimensions:-", Arr2.ndim)

Number of dimensions:- 1
Number of dimensions:- 2


In [ ]:
# Shape of array
print("Shape:-", Arr2.shape)
print("Shape:-", Arr6.shape)

Shape:- (5, 2)
Shape:- (5, 5)


In [ ]:
# Size of array
print("Size: ", Arr2.size)
print("Size: ", Arr3.size)
print("Size: ", Arr6.size)

Size:  10
Size:  20
Size:  25


In [ ]:
# Datatype Of array
print("Type:-", Arr2.dtype)
print("Type:-", Arr3.dtype)
print("Type:-", Arr6.dtype)

Type:- float64
Type:- int64
Type:- float64


In [ ]:
# change the Datatype
print("Integer Array:-",Arr4.astype('int'))
print("Float Array:-",Arr3.astype('float'))

Integer Array:- [10 12 15 17 20]
Float Array:- [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19.]


In [ ]:
# Size of each itme
print("Itemsize:-",Arr1.itemsize)
print("Itemsize:-",Arr2.itemsize)

Itemsize:- 8
Itemsize:- 8


In [ ]:
Arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# The first element
print(Arr3[0])

# The last Element
print(Arr3[-1])


0
19


In [ ]:
Arr7 = np.random.randint(10, size=(3,4))
Arr7

array([[5, 8, 0, 3],
       [0, 8, 7, 6],
       [6, 1, 6, 2]])

In [ ]:
# 2-Dimensional Array
print(Arr7[0,2])

# In=[part1 , part2]=[No.of Row , No.of Column]

3


In [ ]:
Arr7

array([[5, 8, 0, 3],
       [0, 8, 7, 6],
       [6, 1, 6, 2]])

In [ ]:
# Modify Values
Arr3[-1] = "100"
print(Arr3) # One Dimensional
print("---------------------------")
Arr7[(1,2),(2,2)] = "10"
print(Arr7) # Two Dimensional

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18 100]
---------------------------
[[ 5  8  0  3]
 [ 0  8 10  6]
 [ 6  1 10  2]]


In [ ]:
# Mind The Type
Arr7[0,2]= 3.14
Arr7

array([[ 5,  8,  3,  3],
       [ 0,  8, 10,  6],
       [ 6,  1, 10,  2]])

In [ ]:
# First 10 elements
print(Arr3[:10]) # starting from 0 to 10-1

print("--------------------------")

# Elements from the 5th on
print(Arr3[4:]) # starting from 5th to end

print("--------------------------")

# Every four element
print(Arr3[::4])

[0 1 2 3 4 5 6 7 8 9]
--------------------------
[  4   5   6   7   8   9  10  11  12  13  14  15  16  17  18 100]
--------------------------
[ 0  4  8 12 16]


In [ ]:
# Negative Steps
print(Arr3[::-2])

[100  17  15  13  11   9   7   5   3   1]


In [ ]:
# Access Multidimensional Array
Arr7[0,:]

array([5, 8, 3, 3])

In [ ]:
# adding two Arrays
new1 = np.array([1,3,5,7,9])
new2 = np.array([2,4,6,8,10])
print(np.concatenate([new1,new2]))

[ 1  3  5  7  9  2  4  6  8 10]


In [ ]:
# Creating 2 new Arrays
A1 = np.arange(10)
print("A1 =",A1)
print("--------------")
A2 = np.arange(10,20)
print("A2 =",A2)

A1 = [0 1 2 3 4 5 6 7 8 9]
--------------
A2 = [10 11 12 13 14 15 16 17 18 19]


In [ ]:
# Add Operation
print("A1+A2 =",A1 + A2)

print("-------------------")
# Use add() function
A3 = np.add(A1,A2)
print("A3 =",A3)

A1+A2 = [10 12 14 16 18 20 22 24 26 28]
-------------------
A3 = [10 12 14 16 18 20 22 24 26 28]


In [ ]:
# Subtract Operation
# use Subtract Operator
print("A2-A1",A2 - A1)

print("-------------------")

# use subtract() function
A4 = np.subtract(A2,A1)
print("A4 =",A4)

A2-A1 [10 10 10 10 10 10 10 10 10 10]
-------------------
A4 = [10 10 10 10 10 10 10 10 10 10]


In [ ]:
# Multiplication Operation
# use Multiplication Operator
print("A3*A1",A3 * A1)

print("-------------------")

# use multiply() function
A5 = np.multiply(A3,A1)
print("A5 =",A5)

A3*A1 [  0  12  28  48  72 100 132 168 208 252]
-------------------
A5 = [  0  12  28  48  72 100 132 168 208 252]


In [ ]:
print(A3,A1)

[10 12 14 16 18 20 22 24 26 28] [0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Division Opreation
# use Divide Opreator
print("A5/A3",A5 / A3)

print("-------------------")

#use divide() function
A6 = np.divide(A5,A3)
print("A6 =",A6)

A5/A3 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
-------------------
A6 = [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [ ]:
Ar1=np.arange(6).reshape(2,3)
Ar2=np.arange(6,12).reshape(3,2)
print(Ar1)
print(Ar2)

[[0 1 2]
 [3 4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]


In [ ]:
Ar1.dot(Ar2)

array([[ 28,  31],
       [100, 112]])

In [ ]:
A5

array([  0,  12,  28,  48,  72, 100, 132, 168, 208, 252])

In [ ]:
# minimum in Array
print("Small no. =",A5.min())
print("-------------")
# maximum in Array
print("Large no. =",A5.max())
print("-------------")
# Sum of Array
print("Total sum =",A5.sum())

Small no. = 0
-------------
Large no. = 252
-------------
Total sum = 1020


In [ ]:
# medium value in array
print("Medium no. =",A5.mean())

Medium no. = 102.0


In [ ]:
# Absolute value
print(np.abs(A4))
print(np.abs(A3))

[10 10 10 10 10 10 10 10 10 10]
[10 12 14 16 18 20 22 24 26 28]


In [ ]:
# Square Root
print(np.sqrt(A3))
print("-------------------------x")
print(np.sqrt(A5))

[3.16227766 3.46410162 3.74165739 4.         4.24264069 4.47213595
 4.69041576 4.89897949 5.09901951 5.29150262]
-------------------------x
[ 0.          3.46410162  5.29150262  6.92820323  8.48528137 10.
 11.48912529 12.9614814  14.4222051  15.87450787]


In [ ]:
# Exponential Value
print(np.exp(A3))

[2.20264658e+04 1.62754791e+05 1.20260428e+06 8.88611052e+06
 6.56599691e+07 4.85165195e+08 3.58491285e+09 2.64891221e+10
 1.95729609e+11 1.44625706e+12]


In [ ]:
# Square Value
print(np.square(A3))
print("-------------------------x")
print(np.square(A2))

[100 144 196 256 324 400 484 576 676 784]
-------------------------x
[100 121 144 169 196 225 256 289 324 361]


In [ ]:
# numpy.reshape() Function
a1 = np.arange(8)
print("Original array =", a1)
print("--------------------------------------")

# shape array with 2 rows and 4 columns
a2 = np.arange(8).reshape(2, 4)
print("array reshaped with 2 rows and 4 columns = \n",a2)
print("--------------------------------------")

# shape array with 4 rows and 2 columns
a3 = np.arange(8).reshape(4, 2)
print("array reshaped with 4 rows and 2 columns = \n",a3)
print("--------------------------------------")

# Constructs 3D array
a4 = np.arange(8).reshape(2, 2, 2)
print("Original array reshaped to 3D = \n",a4)

Original array = [0 1 2 3 4 5 6 7]
--------------------------------------
array reshaped with 2 rows and 4 columns = 
 [[0 1 2 3]
 [4 5 6 7]]
--------------------------------------
array reshaped with 4 rows and 2 columns = 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]
--------------------------------------
Original array reshaped to 3D = 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
# numpy.ravel() Function
array = np.arange(15).reshape(3, 5)
print("Original array : \n", array)
print("--------------------------------------")

# Convert one numpy array into a single column
# showing output in Python
print("Single Column =", array.ravel())

Original array : 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
--------------------------------------
Single Column = [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [ ]:
# numpy.transpose() Function
# making a 3x3 array
array1 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

# before transpose
print("Before Transpose : \n",array1)
print("--------------------------------------")
# after transpose
print("After Transpose : \n",array1.transpose())

Before Transpose : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------------------------
After Transpose : 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
# stacking Array
# input array
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stacking 2 1-d arrays
c = np.stack((a, b))
print("Stack array : \n",c)

Stack array : 
 [[1 2 3]
 [4 5 6]]


In [ ]:
# Vertical & Horizontal Stacking
a1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
b1 = np.array([[11,12,13],[13,14,15],[16,17,18]])
print("Original array :\n", a1)
print("--------------------------------------")
print("Original array :\n", b1)
print("--------------------------------------")
print("Vertical stacking : \n",np.vstack((a1,b1)))
print("--------------------------------------")
print("Horizontal stacking : \n",np.hstack((a1,b1)))

Original array :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------------------------
Original array :
 [[11 12 13]
 [13 14 15]
 [16 17 18]]
--------------------------------------
Vertical stacking : 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [13 14 15]
 [16 17 18]]
--------------------------------------
Horizontal stacking : 
 [[ 1  2  3 11 12 13]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


In [ ]:
# Simple array
a1 = np.arange(8).reshape(2,4)
a2 = np.arange(8,16).reshape(2,4)

print("Array1 =\n",a1)
print("--------------------------------------")
print("Array2 =\n",a2)
print("--------------------------------------")
a1 + a2

Array1 =
 [[0 1 2 3]
 [4 5 6 7]]
--------------------------------------
Array2 =
 [[ 8  9 10 11]
 [12 13 14 15]]
--------------------------------------


array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [ ]:
# scenario 2
a3 = np.arange(9).reshape(3,3)
a4 = np.arange(3).reshape(1,3)

print("Array1 =\n",a3)
print("--------------------------------------")
print("Array2 =\n",a4)
print("--------------------------------------")
a3 + a4

Array1 =
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
--------------------------------------
Array2 =
 [[0 1 2]]
--------------------------------------


array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [ ]:
# If x=m and y=n,operation will take place
a1 = np.arange(8).reshape(2,4)
a2 = np.arange(8,16).reshape(2,4)

print("Array1 =\n",a1)
print("--------------------------------------")
print("Array2 =\n",a2)
print("--------------------------------------")
a1 + a2

Array1 =
 [[0 1 2 3]
 [4 5 6 7]]
--------------------------------------
Array2 =
 [[ 8  9 10 11]
 [12 13 14 15]]
--------------------------------------


array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [ ]:
# If x=1 and y=n then also operation will take place(same dimension)
a4 = np.arange(3).reshape(1,3)
a5 = np.arange(12).reshape(4,3)

print("Array1 =\n",a4)
print("--------------------------------------")
print("Array2 =\n",a5)
print("--------------------------------------")
a4 + a5

Array1 =
 [[0 1 2]]
--------------------------------------
Array2 =
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
--------------------------------------


array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

In [ ]:
# If y=1 and x=m then also operation will take place,even if
# they are not of the same dimension

a6 = np.arange(4).reshape(4,1)
a7 = np.arange(12).reshape(4,3)

print("Array1 =\n",a6)
print("--------------------------------------")
print("Array2 =\n",a7)
print("--------------------------------------")
a6 + a7

Array1 =
 [[0]
 [1]
 [2]
 [3]]
--------------------------------------
Array2 =
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
--------------------------------------


array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

END